export interface Ciudad {
  codCiudad: number;
  codDepartamento: number;
  nomCiudad: string;
}

// Generated by https://quicktype.io

export interface Departamento {
  codDepartamento: number;
  nombre: string;
}
