// Generated by https://quicktype.io

export interface Cliente {
  primerNombre:    string;
  segundoNombre:   string;
  primerApellido:  string;
  segundoApellido: string;
  codCiudad:       number;
  direccion:       string;
  codigoPostal:    number;
  email:           string;
  telefono:        string;
}
